### PR TITLE
Enable Travis-ci

### PR DESCRIPTION
**Pull request by montefra**
This PR adds a working .travisc.yml file take mixing the astropy-template and the astropy one.

Currently it checks that it is possible to install and run test on linux (with multiple versions) and mac osx (only one case).

### CODE REVIEW

**Comment by montefra** [comment]
@ericmandel : do you get the travis notifications?

**Comment by ericmandel** [comment]
@montefra Not that I know of. The last notification I got was this (yesterday at 4:18 EST):

```
@montefra pushed 3 commits.
28c2c48 Use numpy 1.10 with the astropy ltl version
22bdb28 clear docs warnings
cc68f0b Merge remote-tracking branch 'origin/travis' into travis
```

**Comment by montefra** [comment]
You would notice. If the email notifications are enabled you get emails from builds@travis-ci.org with a subject like: ``Errored: montefra/pyds9#13 (travis - 1eb3342)``. I don't get the mails either. But I was getting them when I had travis enabled on my fork.
According to [this](https://docs.travis-ci.com/user/notifications) build notifications are sent to 

> committer and the commit author, if they are members of the repository (that is, they have push or admin permissions for public repositories

Also [this](https://docs.travis-ci.com/user/notifications#How-is-the-build-email-receiver-determined%3F) says that the mail are sent only if the email in the commit is the same as the github mail (it's my case).
However I can force travis to send notifications only to me.

If you don't want to be notified any time I break something, maybe is better this way :grimacing:

**Comment by ericmandel** [comment]
@montefra I probably don't need to see these ... and if you can save me from receiving extra emails that I don't need to deal with, I'll be grateful! But of course, I'm here to help ...

**Comment by montefra** [comment]
Sounds reasonable. I'll add myself as only receiver for not. Let's see how it go.

**Comment by montefra** [comment]
Finally after many iterations, I managed to make travis happy. I'll soon merge this into trunk and move to windows build and installation via appveyor.

**Comment by ericmandel** [comment]
Very nice work ... this will be helpful in the future. DS9/Python users all owe you gratitude for taking this on!

**Comment by montefra** [comment]
I should have done this long ago... Anyway better late than never.

**Pull request merged**
