### PR TITLE
modify __setattr__ to make setter of @property work

### PR DESCRIPTION
**Pull request by Fmajor**
see issue [#33](https://github.com/ericmandel/pyds9/issues/33)

### CODE REVIEW

**Comment by montefra** [comment]
@Fmajor : thank you for the PR. I don't see problems with merging it. I'll do it in the next days, unless @ericmandel has reserves.

**Comment by ericmandel** [comment]
@Fmajor @montefra I have no objections, and will defer to your Python expertise.

**Comment by montefra** [comment]
@Fmajor : Sorry for the delay.
I have just merged a very big change into master (I make pyds9 look like an astropy affiliated package) so I cannot simply merge your PR anymore. Now we have three choices:

1. I do the merging. However I don't know if github recognize the contribution as yours or mine
2. merge the new master into your branch, resolve the conflicts, commit and push it to your repo. [Here is some info](https://github.com/genome/docs/wiki/How-do-I-fix-my-pull-request-if-it-cannot-be-automatically-merged%3F) and I wouldn't be surprised the PR page gives you some other advice. 
3. we close this PR and you open a new one against the new master applying the changes to pyds9/pyds9.py

Let me know what you prefer.

**Comment by Fmajor** [comment]
I have completed the second suggestion.

**Comment by montefra** [comment]
@Fmajor : thank you very much

**Pull request merged**
