### PR TITLE
Modify the directory structure

### PR DESCRIPTION
**Pull request by montefra**
This series of commits address issue #19. I'm using the [astropy template](http://astropy.readthedocs.org/en/latest/development/affiliated-packages.html?packagename=pyds9) as base.

This way we should get a standard setup for installation (#18), documentation and testing for free.

For now I'm just moving and editing files (starting from directory). Once I've imported all the important things, I'll check that it works.

### CODE REVIEW

**Comment by montefra** [comment]
@ericmandel : for now I have not updated the licence in some of the files (like docs/conf.py).
Your code is released under LGPL, while the astropy template uses 3-clause BSD style license.

Also: pyds9 will look like affilated astropy packages. I don't know if we will become one (your call)

**Comment by ericmandel** [comment]
@montefra  I see your valuable efforts as a move toward full integration with astropy. I support this ... with the caveat that I have no idea what it actually means! But the aim is to provide the Python community with the best tools possible, and I rely on you to define what that means in terms of packaging.

So ... I suspect we want to make the pyds9 license the same as astropy and move toward becoming an affiliated package, right?

**Comment by montefra** [comment]
I'm using the astropy template for a few reasons:

1) since astropy is an important piece of astronomical software and it has a growing community, using their template makes easier for people in the community to interact with pyds9, as @cdeil pointed out somewhere else
2) the template offers already a lot of setups, so it's less work for me :sweat_smile:. Plus I trust their example and experience in packaging.

About being an affiliated package: I don't know exactly. But I guess part of it is about being in a network of (hopefully reliable) packages.
For the licencing: if I remember correctly LGPL and BSD are compatible. I don't think that there are problems in keeping different licences for different pieces of software.

**Comment by ericmandel** [comment]
@montefra @cdeil two good reasons and I am sure you will give good advice about becoming an affiliated package in due course. We don't have to do everything at once.

re license: XPA is under LGPL because that was the __only__ license available in the 1990's ... I've moved to the MIT license for js9 and pyjs9, as that seems to be the standard for Web applications. I do notice that some projects release under two licenses, which might be appropriate in this case.

**Comment by cdeil** [comment]
@ericmandel – If re-licensing XPA and / or pyds9 is possible, +1 to use MIT.

**Comment by ericmandel** [comment]
@cdeil The XPA repository is now under the MIT license, tagged as v2.1.6. We can redo XPA within pyds9 at our leisure.

**Comment by montefra** [comment]
I should have ported all the astropy_helper stuff in pyds9.

There are still things to do:

[ ] figure out what to do with the licences
[ ] figure out how to tell the setup to compile the stuff in cextern
[ ] debug the code (probably it's just matter of making sure that the imports are correct
[ ] make sure that the little documentation we have can be built
[ ] move the test function into the test directory

**Comment by ericmandel** [comment]
In the xpa repository, I changed the license to MIT and we can do that same here. But perhaps pyds9 should follow the astropy lead, if different (although presumably xpa in pyds9 should have the same licence as the repository xpa)?

**Comment by montefra** [comment]
I think that having xpa with the same licence it's easier, unless MIT has problems with the 3-clause BSD (which I doubt)

**Comment by cdeil** [comment]
MIT and BSD-3 are perfectly compatible, having everything under MIT is just fine, there's no reason / advantage to switching to BSD-3 that I know of.

And @ericmandel – bit thanks for re-licensing under MIT so that we don't have to worry about license compatibility issues with Astropy et al.

**Comment by ericmandel** [comment]
@cdeil @montefra OK, even though we have 2 different threads on this, the answer seems to be the same: we can use MIT for pyds9, XPA already having been changed in the repository (and we should update the XPA inside pyds9 to reflect this).

**Comment by montefra** [comment]
@ericmandel : yes :blush: 

I'll try to review the changes up to now and merge in ``devel`` branch in the next days. After I've done it, I'll come back to you about the MIT licensed xpa.

**Comment by montefra** [comment]
I'll update xpa to the latest version and merge into "devel".

Then I'll try to figure out how to build it as in #18, #26

**Comment by montefra** [comment]
If there are no objections I'll merge this branch into devel in the next days.

Then try to figure out how to make xpa using the astropy machinery.

**Comment by ericmandel** [comment]
Yes, it's fine to merge ...

**Pull request merged**
