### PR TITLE
Bump revision from 1.8.1 to 1.9.dev in pyds9.py

### PR DESCRIPTION
**Pull request by DougBurke**
I assume version updates are being handled manually, and that we use
"dev" for development builds (based on the value currently in setup.py).

### CODE REVIEW

**Comment by ericmandel** [comment]
Yes, but its worse than that ... there is a version var in pyds9.py which looks like its currently set to 1.8.1!

**Comment by DougBurke** [comment]
Well, not now - as of 1784fd8 it's explicitly taken from `setup.cfg`

**Comment by ericmandel** [comment]
And so probably should be removed from pyds9.py, so avoid some confusion?

**Comment by DougBurke** [comment]
I removed the `__version__` variable from pyds9.py in  1784fd8 - do you see another one?

**Pull request merged**
